In [ ]:
import numpy as np

In [ ]:

a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#  Scalar
# Arithematic
print(a1)
print(a1*2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [39]:
# Relational
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
#  Vector
# Arithematic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])