In [ ]:
import numpy as np

In [ ]:

a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)


In [ ]:
#  Scalar
print(a1)
print(a1*2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [28]:
# Relational
a2>15

NameError: name 'a2' is not defined