In [ ]:
import numpy as np 

In [9]:

a1=np.random.random((3,3))
a1=np.round(a1*100)
a1


array([[75., 62., 56.],
       [40., 19., 56.],
       [80., 60., 20.]])

In [12]:
# 1 : min / max / sum /prod

print(np.min(a1))
print(np.max(a1))
print(np.sum(a1))
print(np.prod(a1))

19.0
80.0
468.0
1063931904000000.0


In [ ]:
# We can also find max / min etc  , of each row and column 
#  0 ---> for Column     ,,,,, 1 ---> for Row 

print(np.max(a1,axis=1))
print(np.min(a1,axis=0))

[75. 56. 80.]
[40. 19. 20.]


In [15]:
# 2 : mean / median / std / var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

52.0
56.0
20.45591465675501
418.44444444444446


Dot Product --> Column of 1st array should be equal to Row of second array

In [ ]:
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

In [ ]:
np.dot(a3,a2)

array([[164, 203, 242, 281],
       [200, 248, 296, 344],
       [236, 293, 350, 407],
       [272, 338, 404, 470]])

Log and Exponent 

In [54]:
print(np.log(a1))
print(np.exp(a1))

[[4.31748811 4.12713439 4.02535169]
 [3.68887945 2.94443898 4.02535169]
 [4.38202663 4.09434456 2.99573227]]
[[3.73324200e+32 8.43835667e+26 2.09165950e+24]
 [2.35385267e+17 1.78482301e+08 2.09165950e+24]
 [5.54062238e+34 1.14200739e+26 4.85165195e+08]]


Round , Floar , ceil 

In [56]:
print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))

[[31. 85. 92.]
 [62. 41. 21.]]
[[32.  6. 46.]
 [76. 13. 15.]]
[[65. 55. 47.]
 [23. 55. 29.]]
