In [ ]:
import numpy as np



Creating 1st numpy array 1st way (1D)

In [10]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

2D

In [11]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

3D

In [12]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Change data-type

In [ ]:
np.array([2,3,0] ,dtype=bool)


array([ True,  True, False])

Other Methods of creating array 

In [ ]:
# arange
np.arange(1,11) #1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# reshape
np.arange(1,13).reshape(2,6)#2D


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
#.ONES
np.ones((3,4))   

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
#ZEROS
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# Random
np.random.random((3,4))

array([[0.2227693 , 0.24117034, 0.6043167 , 0.15429144],
       [0.39593601, 0.46318904, 0.38355466, 0.79709302],
       [0.22239275, 0.22912792, 0.19801197, 0.06250374]])

In [ ]:
# Linspace
np.linspace(-10,10,10)  # start-stop-no.of term

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# Identity
np.identity(3)  # one Diagonal is ones , other all zeros

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])