In [26]:
import numpy as np 

RESHAPE  ----Done already 
TRANSPOSE  ----> Array ko ulta krta hai , 3x4 array ko 4x3 kr deta hai .. 
RAVEL  --->  3D,2D...  array ko 1D mai convert 

In [27]:
a2=np.arange(12).reshape(3,4)
print(a2)

np.transpose(a2)       # a2.T ( 2nd syntax)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [28]:
a2.ravel

<function ndarray.ravel>

                                                        STACKING

In [29]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12).reshape(3,4)

In [30]:
#      horizontal stacking ---> Joins them horizontally
np.hstack((a4,a5))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [31]:
#      vertical stacking ---> Joins them vertically
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

                                                SPLITTING--> Splits two arrays

In [34]:
np.hsplit(a4,2)  # a4 array ko 2 equal parts mai split krdo horizontally
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]