In [1]:
import numpy as np 

RESHAPE  ----Done already 
TRANSPOSE  ----> Array ko ulta krta hai , 3x4 array ko 4x3 kr deta hai .. 
RAVEL  --->  3D,2D...  array ko 1D mai convert 

In [ ]:
a2=np.arange(12).reshape(3,4)
print(a2)

np.transpose(a2)       # a2.T ( 2nd syntax)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.ravel

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])