In [1]:
import numpy as np

                                                                     INDEXING  --- only one item can be fetched 

In [2]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(27).reshape(3,3,3)

In [3]:
#   1D

print(a1)
a1[-1]    # Fetch last element 

[0 1 2 3 4 5 6 7 8 9]


9

In [4]:
#  2D

print(a2)
a2[1,2]   # 1--for(row)       2---for(column)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


6

In [5]:
#  3D --  it's a combination of two 2D

print(a3)
a3[1,0,1]   #  1--for(which 2D)     # 0--for(row no of that 2D)   # 1 --for(col no of that 2D)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


10

                                                                          SLICING -- Can fetch multiple items

                                                                            1D

In [6]:
print(a1)
a1[2:5]

[0 1 2 3 4 5 6 7 8 9]


array([2, 3, 4])

                                                                            2D

In [7]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
a2[:,2]   # row sarey fetch krdo , column only 3rd wla karo

array([ 2,  6, 10])

In [9]:
a2[1:,1:3]    # from fow 1st index to all , from col 1st index to col 3rd-1

array([[ 5,  6],
       [ 9, 10]])

In [10]:
a2[::2,::3]   #  ::2 --> All alternate rows , ::3 --> Takes every 3rd col

array([[ 0,  3],
       [ 8, 11]])

                                                                            3D

In [11]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
a3[1]  # Prints whole 2nd 2D array

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [13]:
a3[::2]  # prints 1st and last 2D array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
a3[0,1,:]   # prints 2nd row of 1st 2D array

array([3, 4, 5])

In [15]:
a3[1,:,1]   # prints 2nd col of 2nd 2D array

array([10, 13, 16])

In [16]:
a3[::2,0,::2]   

array([[ 0,  2],
       [18, 20]])