In [2]:
import numpy as np

In [5]:
# 1D
a1=np.arange(10)
for i in a1:
    print(i)


0
1
2
3
4
5
6
7
8
9


In [ ]:
# 2D
a2=np.arange(12).reshape(3,4)
for i in a2 :
    print(i)              # prints each row at a time

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [7]:
#  3D
a3=np.arange(27).reshape(3,3,3)
for i in a3 :
    print(i)             # prints each 2D array at a time

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
    print(i)