In [2]:
import numpy as np

Two types of indexing is there 
    1-Fancy Indexing 
    2-Boolean Indexing 

                                                    1-Fancy Indexing 

In [ ]:
a=np.arange(24).reshape(6,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [7]:
# Question - I want output 1st , 3rd , 4th and 6th row 
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [8]:
# Question - I want output 1st , 3rd and 4th column 
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

                                                    2-Boolean Indexing 


In [ ]:
a=np.random.randint(1,100,24).reshape(6,4)    # randint()  , generates numbers randomly with given range { Start(1) - To(100) - no of items(24) }
print(a)

[[25 18 79 12]
 [59 46 11 50]
 [ 1 66  8 28]
 [63 86 56 38]
 [95 43 51 30]
 [89 25 84  3]]
