Broadcasting is an conceptual thing :
Broadcasting : Simpally tells us that you can do Arithematic opertions between two Dis-similar arrays with Broadcasting by following some rules 

Rule 1 - Make the two array have same *number*  of dimension 
        If the numbers of dimensions of the array are different , the add new dimension with size '1' to the head of the array with similar number of dimension

Rule 2 - Make each dimension of the two arrays the same size 
        If the size of each dimension of the two arrays do not match , dimension with size '1' are streched to the size of the other array 

Rule 3 - If there is a dimension whose size is not '1' in either of the two arrays , it can not be broadcasted 


In [ ]:
import numpy as np 

In [ ]:
# will work , because all rules work here 
a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(a+b)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
# will not work
a = np.arange(12).reshape(3,4)
b = np.arange(3)
print(a+b)

In [15]:
a=np.arange(3).reshape(1,3)
b=np.arange(3).reshape(3,1)
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [20]:
# will not work 
a=np.arange(12).reshape(3,4)
b=np.arange(12).reshape(4,3)
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
# Will not work
a=np.arange(16).reshape(4,4)
b=np.arange(4).reshape(2,2)
print(a+b)